### ISSUE TITLE
你好，请问需要什么环境

### ISSUE THREAD

**Issue by liang112** [Szczecin/Secret-Sharing#1]
你好，请问需要什么环境

**Comment by liang112** [comment]
什么版本的python，还有包之类的，谢谢，拜托了

**Comment by Szczecin** [comment]
Anaconda（应该自带Jupyter notebook），剩下的只能你打开[FL.ipynb](https://github.com/Szczecin/Secret-Sharing/blob/main/FL.ipynb)看了，里面东西应该比较详细，其他的我不愿多说，数据（训练集、测试集等）需要靠自己去弄

**Comment by liang112** [comment]
你好，请问Python用的什么版本，还有Pytorch、TensorFlow，Phe，syft 的版本，因为我在Jupyter notebook上运行报错了，可能版本不对，实在是不好意思打扰你。

**Comment by liang112** [comment]
本科的论文选到了这个，难度实在是有点大

**Comment by liang112** [comment]
本科选了这个，很难，很需要您的帮助

**Comment by liang112** [comment]
急，可有偿，给个环境依赖，比如Pytorch、TensorFlow，Phe，syft 的版本，我的vx：13622904428

**Comment by liang112** [comment]
我配的环境不兼容，syft和tensorflow

**Comment by liang112** [comment]
哥们，我已经跑出来了，请问有更详细的文档，论文之类的吗，详细一点的那些，可以有偿

**Comment by liang112** [comment]
想要论文

**Comment by liang112** [comment]
请问有联系方式吗

**Comment by Szczecin** [comment]
如果你仔细看了readme.md，你就会发现这个内容是有关纵向联邦的秘密分享实现实验，是我本科的毕设内容，我不想把论文直接展示，也不建议你搬仓库，这个实验的内容在另外的论文上被算法用证，希望你明白重复意味着什么
